allow-lan: false
mode: rule
log-level: info
ipv6: false
dns:
  enable: true
  ipv6: false
  nameserver:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  enhanced-mode: redir-host
  default-nameserver:
  - 223.5.5.5
  - 180.76.76.76
  - 119.29.29.29
  proxy-server-nameserver:
  - 223.5.5.5
  - 180.76.76.76
  - 119.29.29.29
  respect-rules: true
  nameserver-policy:
    rule-set:cn_domain:
    - 223.5.5.5
    - 180.76.76.76
    - 119.29.29.29
listeners:
- name: chain-entry-http-2002
  type: http
  port: 2002
  listen: 0.0.0.0
  users:
  - username: admin12
    password: Dd;'2131801a
- name: chain-entry-http-2001
  type: http
  port: 2001
  listen: 0.0.0.0
  users:
  - username: admin123
    password: admin1234
rules:
- IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
- IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
- IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
- IP-CIDR,240.0.0.0/4,DIRECT,no-resolve
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,private,DIRECT
- RULE-SET,cn_domain,DIRECT
- RULE-SET,cn_ip,DIRECT,no-resolve
- MATCH,102.112217.xyz
proxy-groups:
- name: 自动选择
  type: url-test
  proxies:
  - ss-0.0.0.0-852044
  - 101.112217.xyz
  - 102.112217.xyz
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - ss-0.0.0.0-852044
  - 101.112217.xyz
  - 102.112217.xyz
  - DIRECT
- name: chain-level2-urltest
  type: url-test
  proxies:
  - 101.112217.xyz
  - 102.112217.xyz
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
tcp-concurrent: true
unified-delay: true
connection-timeout: 5
external-controller: 127.0.0.1:19093
x-split-route: true
keep-alive-interval: 30
keep-alive-idle: 600
sniffer:
  enable: false
geodata-mode: false
rule-providers:
  cn_domain:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs
    path: ./ruleset/cn_domain.mrs
    interval: 86400
  cn_ip:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs
    path: ./ruleset/cn_ip.mrs
    interval: 604800
  private:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs
    path: ./ruleset/private.mrs
    interval: 86400
proxies:
- name: ss-0.0.0.0-852044
  type: ss
  server: 42.193.146.146
  port: 18000
  cipher: aes-128-gcm
  password: 25b40997-2d5f-4996-bb71-33a5975dfa36
  udp: true
- name: 101.112217.xyz
  type: ss
  port: 12093
  cipher: 2022-blake3-aes-128-gcm
  password: ZnVHrxWfQFmUQ+1OsyakOA==
  udp: true
  server: 101.112217.xyz
- name: 102.112217.xyz
  type: ss
  port: 12093
  cipher: 2022-blake3-aes-128-gcm
  password: ZnVHrxWfQFmUQ+1OsyakOA==
  udp: true
  server: 102.112217.xyz
